---
- name: MySQL | Install Server
  become: yes
  apt: pkg=mysql-server state=installed
  tags: mysql-server

- name: MySQL | Update my.cnf
  become: yes
  template: src=14.04/my.cnf dest=/etc/mysql/my.cnf
  notify:
    - restart mysql
  when: ansible_distribution_version == '14.04'
  tags: mysql-server

- name: MySQL | Update my.cnf
  become: yes
  template: src=16.04/mysqld.cnf dest=/etc/mysql/mysql.conf.d/mysqld.cnf
  notify:
    - restart mysql
  when: ansible_distribution_version == '16.04'
  tags: mysql-server

- name: MySQL | Test root has blank password
  shell: mysql -u root --password= --disable-column-names --batch -e 'select 1'
  register: mysql_has_blank_root_password
  ignore_errors: true
  tags: mysql-server

- name: MySQL | Remove anonymous users
  ignore_errors: yes
  mysql_user: name='' host={{ item }}
      login_host={{ mysql_host }}
      login_user=root
      login_password=
      state=absent
  with_items:
   - localhost
   - "127.0.0.1"
   - "%"
   - "{{ ansible_hostname }}"
  when: mysql_has_blank_root_password.rc == 0
  tags: mysql-server

# Assume basic MySQL security is already managed if the root password is not blank.
- name: MySQL | Secure Installation
  include: mysql_secure_installation.yml
  when: mysql_has_blank_root_password.rc == 0
  tags: mysql-server
