---
# @see https://github.com/PCextreme/ansible-role-mariadb/blob/master/tasks/mysql_secure_installation.yml

- name: Remove anonymous users
  command: 'mysql -u root --password={{ mysql_root_pass }} -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  become: yes
  command: 'mysql -u root --password={{ mysql_root_pass }} -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: False

- name: Remove test database and access to it
  become: yes
  command: 'mysql -u root --password={{ mysql_root_pass }} -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  become: yes
  command: 'mysql -u root --password={{ mysql_root_pass }} -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
