---
- hosts: drupalbox
  vars:
    hostname: drupalbox
    rvm1_user: vagrant
    rvm1_install_path: /home/vagrant/.rvm
  vars:
    php_ini_sendmail_path: "/usr/local/bin/mhsendmail"
  vars_files:
    - vars/default/common.yml
    - vars/dev/mysql.yml
    - vars/dev/apache.yml
    - vars/dev/php.yml
  roles:
    - { role: init }
    - { role: common }
    - { role: openssh }
    - { role: git }
    - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: true }
    - { role: memcached }
    - { role: mailhog }
    - { role: apache }
    - { role: mysql-client }
    - { role: mysql-server }
    - { role: php5, when: ansible_distribution_version == '14.04' }
    - { role: php7, when: ansible_distribution_version == '16.04' }
    - { role: composer }
    - { role: phpmyadmin }
    - { role: drush }
    - { role: drupal-console }
    - { role: nodejs }
    - { role: phantomjs }
    - { role: duplicity }
    - { role: drupalbox }
