---
- name: Drupal Console | Check install
  stat: path=/usr/local/bin/drupal
  register: drupal_console_phar
  tags: drupal-console

- name: Drupal Console | Download
  become: yes
  get_url: url=https://drupalconsole.com/installer
           dest=/usr/local/bin/drupal
           mode=u+rwx,g+rx,a+rx
  when: drupal_console_phar.stat.exists == False
  tags: drupal-console
