---
- name: NodeJS | Add apt key
  sudo: yes
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
           state=present
  tags: nodejs

- name: NodeJS | Add apt repository
  sudo: yes
  apt_repository: repo='{{ item }}'
                  state=present
  with_items:
    - 'deb https://deb.nodesource.com/node_0.12 trusty main'
    - 'deb-src https://deb.nodesource.com/node_0.12 trusty main'
  tags: nodejs

- name: NodeJS | Update apt cache
  sudo: yes
  apt: update-cache=yes
  tags: nodejs

- name: NodeJS | Install NodeJS
  sudo: yes
  apt: pkg=nodejs
       state=present
  tags: nodejs
