---
solr_mirror: https://archive.apache.org/dist/lucene/solr/
solr_version: 4.5.1

slf4j_lib_path: "{{ solr_version_src_dir }}/example/lib/ext"

solr_app_name: solr

solr_root_src_dir: /usr/local/src/solr
solr_root_dir: /usr/share/solr
solr_home_dir: "{{ solr_root_dir }}/{{ solr_version }}"
solr_data_dir: /var/lib/solr

solr_version_dir: solr-{{ solr_version }}
solr_version_war: solr-{{ solr_version }}
solr_version_file: "{{ solr_version_dir }}.tgz"
solr_version_src_dir: "{{ solr_root_src_dir }}/{{ solr_version_dir }}"

solr_app_user: jetty
solr_app_group: jetty

solr_cores: []
