---
- name: Composer | Install Composer
  become: yes
  shell: curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f composer.phar {{ composer_path }}
         creates={{ composer_path }}
  tags: composer

- name: Composer | self-update
  become: yes
  shell: composer self-update
  tags: composer

- name: Composer | Update .bashrc
  lineinfile: dest=/home/{{ ansible_user_id }}/.bashrc
              regexp="export PATH=\"$HOME/.config/composer/vendor/bin:$PATH\""
              line="export PATH=\"$HOME/.config/composer/vendor/bin:$PATH\""
              insertafter=EOF
              state=present
  tags: composer
