---

- name: Solr | Copy cores
  become: yes
  copy:
    src: "cores/{{ item }}"
    dest: "{{ solr_home_dir }}/cores"
    owner: "{{ solr_app_user }}"
    group: "{{ solr_app_group }}"
  with_items: "{{ solr_cores }}"
  tags: solr

- name: Solr | Create Data Directories
  become: yes
  file:
    path: "{{ solr_data_dir }}/{{ item }}/data"
    owner: "{{ solr_app_user }}"
    group: "{{ solr_app_group }}"
    recurse: true
    state: directory
  with_items: "{{ solr_cores }}"
  tags: solr

- name: Solr | Generate solr.xml
  become: yes
  template:
    src: solr.xml.j2
    dest: "{{ solr_home_dir }}/solr.xml"
    owner: "{{ solr_app_user }}"
    group: "{{ solr_app_group }}"
  tags: solr
