---

- name: Solr | Create Solr Directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ solr_app_user }}"
    group: "{{ solr_app_group }}"
  with_items:
    - "{{ solr_root_src_dir }}"
    - "{{ solr_home_dir }}"
    - "{{ solr_data_dir }}"
    - "{{ solr_home_dir }}/cores"
  tags: solr

- name: Solr | Check download exists
  become: yes
  stat:
    path: "{{ solr_root_src_dir }}/{{ solr_version_file }}"
  register: solr_src_file_exists
  tags: solr
